version: "3.8"

services:
  test-service:
    build: .
    container_name: test-service
    command: python -m uvicorn test:app --host 0.0.0.0 --port 8016
    volumes:
      - ./Standards:/app/Standards
      - ./chroma_store:/app/chroma_store
      - ./output:/app/output
    ports:
      - "8016:8016"

  bot-service:
    build: .
    container_name: bot-service
    command: python -m uvicorn bot:app --host 0.0.0.0 --port 8017
    volumes:
      - ./Standards:/app/Standards
      - ./chroma_store:/app/chroma_store
    ports:
      - "8017:8017"
    depends_on:
      - test-service

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - bot-service
